apiVersion: skaffold/v1beta2
kind: Config
build:
    local:
        push: false
    artifacts:
        - image: skmani2/multi-client
          context: web/multi-client
          docker:
            dockerfile: Dockerfile
          sync:
            '**/*.js': .
deploy:
    kubectl:
        manifests:
            - k8s-multicontainer/web-deployment.yaml
            - k8s-multicontainer/web-service.yaml
        