apiVersion: v1
kind: Service
metadata:
    name: nodeweb-srvc
spec:
    type: NodePort
    ports:
        - port: 30040
          targetPort: 8080
          nodePort: 30001
    selector:
        component: nodeweb
        