apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-claim
    namespace: test-kube
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
        