apiVersion: v1
kind: Service
metadata:
    name: multi-client-srvc
    namespace: test-kube
spec:
    type: ClusterIP
    ports:
        - port: 30001
          targetPort: 30001
    selector:
        component: multi-client
        